logging:
  config: classpath:config/logback-dev.xml
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sweb?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&useSSL=false
    username: root
    password: root
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
    asyncInit: true
  # Redis
  redis:
    database: 0
    port: 23333
    host: 127.0.0.1
    password: justbecause
    pool:
      max-active: 20
  # Dubbo
  dubbo:
    application:
      name: provider
    scan: io.tooko.sboot.service
    protocol:
      name: dubbo
      port: 20881
    registry:
      address: zookeeper://127.0.0.1:2181
